# Generated by Django 3.2.3 on 2021-05-30 08:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('model_fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=[], max_length=250, null=True), size=None)),
                ('mapped_fields', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, default=dict, null=True), blank=True, null=True, size=None)),
                ('foreign_key_mapped_fields', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, default=dict, null=True), blank=True, null=True, size=None)),
                ('app_label_name', models.CharField(max_length=500)),
                ('file_input', models.FileField(blank=True, null=True, upload_to='', verbose_name='File Path')),
            ],
        ),
    ]
